### ISSUE TITLE
Add HuggingFace Neuron TGI Container support to Neuron V2.18.2 and V2.19.1

### ISSUE THREAD

**Issue by cszhz** [huggingface/optimum-neuron#678] opened 2024-08-09 02:07 UTC
### Feature request

The official Text Generation Inference has not been upgraded for several months.
The latest Neuron version is V2.19.1, however optimum-neuron container is still staying in V2.18.0.

Please add support on Neuron V2.18.2 and V2.19.1

https://huggingface.co/docs/optimum-neuron/en/containers

### Motivation

optimum-neuron container neuron version is too low and cause this issue when hosting new neuron model
```
RuntimeError: Pretrained model is compiled with neuronx-cc(2.13.72.0+78a426937) newer than current compiler (2.13.66.0+6dfecc895), which may cause runtime incompatibilities.
```

### Your contribution

I personally build a docker container temporarily fix this issue.

https://hub.docker.com/r/cszhzleo/tgi-2.18.2

**Comment by karllessard** [comment] 2024-08-19 21:43
+1, now that [v0.0.24](https://github.com/huggingface/optimum-neuron/releases/tag/v0.0.24) of optimum-neuron has been released, when can we expect a container that supports this version? As I'm getting error when I tried to build the image myself, I would love only having to download it. With flash attention support, version 2.19.1 is quite interesting to try.

**Comment by JingyaHuang** [comment] 2024-08-22 12:50
Hi, we [submitted updates](https://github.com/awslabs/llm-hosting-container/pull/87) to the official neuron tgi containers repo, which supports neuron SDK 2.19.1 + optimum-neuron v0.0.24. Its release will be handled by the AWS Sagemaker team, we will keep you posted and update the URL in our doc once it's done.

**Comment by JingyaHuang** [comment] 2024-08-22 12:57
correct me if I'm wrong @dacorvo, the one with Neuron SDK 2.18.0 + Optimum-neuron v0.0.23 has been released for a while, and we don't have an official release with Neuron SDK 2.18.2 due to some regressions.

**Comment by JingyaHuang** [comment] 2024-08-22 21:48
Hi @cszhz @karllessard The TGI Container for Optimum Neuron v0.0.24 + Neuron sdk 2.19.1 has been released: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-tgi-0.0.24-pt-2.1.2-inf-neuronx-py310.

Closing the issue, feel free to re-open if there are further questions.

**Closed by JingyaHuang** 2024-08-22 21:48 UTC

**Comment by dacorvo** [comment] 2024-08-26 08:11
> correct me if I'm wrong @dacorvo, the one with Neuron SDK 2.18.0 + Optimum-neuron v0.0.23 has been released for a while, and we don't have an official release with Neuron SDK 2.18.2 due to some regressions.

Yes, you're correct.
