### ISSUE TITLE
ON compile LCM-SD broken with cannot import NeuronLatentConsistencyModelPipeline error

### ISSUE THREAD

**Issue by kct22aws** [huggingface/optimum-neuron#489] opened 2024-02-16 23:54 UTC
### System Info

```shell
optimum                       1.17.0
optimum-neuron                0.0.13
Python 3.10
Ubuntu 22.04
Neuron 2.17.0
```

### Who can help?

@JingyaHuang Official code snippet in https://huggingface.co/docs/optimum-neuron/tutorials/stable_diffusion#compile-lcm is broken with following error: 
```
    from optimum.neuron import NeuronLatentConsistencyModelPipeline
ImportError: cannot import name 'NeuronLatentConsistencyModelPipeline' from 'optimum.neuron' (/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/neuron/__init__.py)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Use AWS inf2 instance, install Neuron 2.17.0, then install current version of transformers, accelerate, diffusers, evaluate, datasets. Then install ON via pip install optimum[neuronx]. Then run [code](https://huggingface.co/docs/optimum-neuron/tutorials/stable_diffusion#compile-lcm) as a Python script. 

### Expected behavior

Expect the code to complete the run.

**Comment by JingyaHuang** [comment] 2024-02-19 10:27
Hi @kct22aws, thanks fore reporting the issue. The error is introduced by the refactoring of the model registration mechanism in Optimum 1.17.0, it is fixed by #414, and we are planning for a release for it. In the future we will also pin optimum version to avoid breaking changes from Optimum's side. 

If you are testing something, you could use optimum < 1.17 until the new release of Optimum Neuron.

**Comment by JingyaHuang** [comment] 2024-02-19 14:18
Optimum Neuron 0.0.19 is out, could you try if the issue is solved? Thanks! 
https://pypi.org/project/optimum-neuron/0.0.19/

**Comment by JingyaHuang** [comment] 2024-02-20 14:15
Close as it should have been solved with the latest release. Feel free to reopen if there are any follow-up questions.

**Closed by JingyaHuang** 2024-02-20 14:15 UTC
Labels: bug
